apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: marketing-site
  description: |
    A Gatsby application for generating the Roadie marketing site. Includes
    blog posts, legal policies, landing pages etc.
  annotations:
    github.com/project-slug: RoadieHQ/marketing-site
    lighthouse.com/website-url: https://roadie.io/
    backstage.io/techdocs-ref: url:https://github.com/RoadieHQ/marketing-site/tree/main
spec:
  type: website
  owner: user:david
  lifecycle: production
