# When Backstage was first released, it didn't have a service catalog at all. I wrote
# one blog post before the service catalog came along and another afterwards.
# Now that the service catalog is part of the default Backstage experience, these posts are
# essentially duplicate content.
[[redirects]]
  from = "/blog/backstage-docker-compose/"
  to = "/blog/backstage-docker-service-catalog/"
  force = true

# Supporting a legacy URL scheme which existed when the site was first published.
[[redirects]]
  from = "/terms/"
  to = "/legal-notices/website-terms/"
  force = true

# Supporting a legacy URL scheme which existed when the site was first published.
[[redirects]]
  from = "/privacy/"
  to = "/legal-notices/privacy-notice/"
  force = true

[[redirects]]
  from = "/careers/"
  to = "https://careers.roadie.io"
  force = true

# Proxy for the plausible.io tracker. https://plausible.io/docs/proxy/guides/netlify
[[redirects]]
  from = "/plaus/js/script.js"
  to = "https://plausible.io/js/plausible.js"
  status = 200
  force = true

# Proxy for the plausible.io tracker. https://plausible.io/docs/proxy/guides/netlify
[[redirects]]
  from = "/plaus/api/event"
  to = "https://plausible.io/api/event"
  status = 200
  force = true

# Supporting external links to a policy which was orignally put on the website with a
# mis-spelled URL.
[[redirects]]
  from = "/legal-notices/evaluation-licence/"
  to = "/legal-notices/evaluation-license/"
  force = true

# Supporting external links to a policy which was orignally put on the website with a
# mis-spelled URL.
[[redirects]]
  from = "/legal-notices/evaluation-licence/v1/"
  to = "/legal-notices/evaluation-license/v1/"
  force = true

# Supporting US and UK spelling of modelling and modeling. The single-l version is linked from
# few places on the web.
[[redirects]]
  from = "/blog/modeling-software-backstage/"
  to = "/blog/modelling-software-backstage/"
  force = true

[[redirects]]
  from = "/docs/details/whitelisting-roadie-traffic/"
  to = "/docs/details/allowlisting-roadie-traffic/"
  force = true

[[redirects]]
  from = "/docs/getting-started/getting-started-for-admins/"
  to = "/docs/getting-started/install-github-app/"
  force = true

[[redirects]]
  from = "/docs/integrations/github-app-permissions/"
  to = "/docs/details/github-app-permissions/"
  force = true

[[redirects]]
  from = "/docs/getting-started/updating-the-ui/"
  to = "/docs/details/updating-the-ui/"
  force = true

[[redirects]]
  from = "/docs/integrations/required-annotations/"
  to = "/docs/details/required-annotations/"
  force = true

[[redirects]]
  from = "/docs/configurations/tech-radar/"
  to = "/docs/integrations/tech-radar/"
  force = true

[build]
  publish = "public"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"
