# When Backstage was first released, it didn't have a service catalog at all. I wrote
# one blog post before the service catalog came along and another afterwards.
# Now that the service catalog is part of the default Backstage experience, these posts are
# essentially duplicate content.
[[redirects]]
  from = "/blog/backstage-docker-compose/"
  to = "/blog/backstage-docker-service-catalog/"
  force = true

# Supporting a legacy URL scheme which existed when the site was first published.
[[redirects]]
  from = "/terms/"
  to = "/legal-notices/website-terms/"
  force = true

# Supporting a legacy URL scheme which existed when the site was first published.
[[redirects]]
  from = "/docs/openapi"
  to = "/docs/api/authorization"
  force = true

# Supporting a legacy URL scheme which existed when the site was first published.
[[redirects]]
  from = "/privacy/"
  to = "/legal-notices/privacy-notice/"
  force = true

[[redirects]]
  from = "/careers/"
  to = "https://careers.roadie.io"
  force = true

# Proxy for the plausible.io tracker. https://plausible.io/docs/proxy/guides/netlify
[[redirects]]
  from = "/plaus/js/script.js"
  to = "https://plausible.io/js/plausible.js"
  status = 200
  force = true

# Proxy for the plausible.io tracker. https://plausible.io/docs/proxy/guides/netlify
[[redirects]]
  from = "/plaus/api/event"
  to = "https://plausible.io/api/event"
  status = 200
  force = true

# Supporting external links to a policy which was orignally put on the website with a
# mis-spelled URL.
[[redirects]]
  from = "/legal-notices/evaluation-licence/"
  to = "/legal-notices/evaluation-license/"
  force = true

# Supporting external links to a policy which was orignally put on the website with a
# mis-spelled URL.
[[redirects]]
  from = "/legal-notices/evaluation-licence/v1/"
  to = "/legal-notices/evaluation-license/v1/"
  force = true

# Supporting US and UK spelling of modelling and modeling. The single-l version is linked from
# few places on the web.
[[redirects]]
  from = "/blog/modeling-software-backstage/"
  to = "/blog/modelling-software-backstage/"
  force = true

[[redirects]]
  from = "/docs/details/whitelisting-roadie-traffic/"
  to = "/docs/details/allowlisting-roadie-traffic/"
  force = true

[[redirects]]
  from = "/docs/getting-started/getting-started-for-admins/"
  to = "/docs/getting-started/install-github-app/"
  force = true

[[redirects]]
  from = "/docs/integrations/github-app-permissions/"
  to = "/docs/details/github-app-permissions/"
  force = true

[[redirects]]
  from = "/docs/getting-started/updating-the-ui/"
  to = "/docs/details/updating-the-ui/"
  force = true

[[redirects]]
  from = "/docs/integrations/required-annotations/"
  to = "/docs/details/required-metadata/"
  force = true

[[redirects]]
  from = "/docs/configurations/tech-radar/"
  to = "/docs/integrations/tech-radar/"
  force = true

# We are inundated by spam security reports since we added this. It's not worth it.
[[redirects]]
  from = "/security/responsible-disclosure/"
  to = "/"
  force = true

# We'll create a dedicated landing page for people coming from KubeCon 
[[redirects]]
  from = "/kubernetes/"
  to = "/backstage/plugins/kubernetes/"
  force = true

# To be later filled in with a typeform URL 
[[redirects]]
  from = "/techinsights-demo-backstagecon/"
  to = "/request-demo/"
  force = true

# There's no generic product page so we redirect to the first one
[[redirects]]
  from = "/product/"
  to = "/product/catalog/"
  force = true

[[redirects]]
  from = "/docs/scaffolder-cookbook/*"
  to = "/docs/scaffolder/:splat"
  force = true

[[redirects]]
  from = "/docs/details/scaffolder/"
  to = "/docs/scaffolder/writing-templates/"
  force = true

[[redirects]]
  from = "/docs/custom-plugins/"
  to = "/docs/custom-plugins/getting-started/"
  force = true

[[redirects]]
  from = "/docs/custom-plugins/proxy/"
  to = "/docs/custom-plugins/connectivity/proxy/"
  force = true

[[redirects]]
  from = "/docs/integrations/home-page-markdown/"
  to = "/docs/integrations/markdown-card/"
  force = true

[[redirects]]
  from = "/docs/details/location-management/"
  to = "/docs/catalog/location-management/"
  force = true

[[redirects]]
  from = "/docs/details/showing-dependencies/"
  to = "/docs/catalog/showing-dependencies/"
  force = true

[[redirects]]
  from = "/docs/details/decorating-components/"
  to = "/docs/catalog/decorating-components/"
  force = true

[[redirects]]
  from = "/docs/details/unregister-components/"
  to = "/docs/catalog/unregister-components/"
  force = true

[[redirects]]
  from = "/docs/details/previewing-changes/"
  to = "/docs/catalog/previewing-changes/"
  force = true

[[redirects]]
  from = "/docs/details/troubleshooting-the-catalog/"
  to = "/docs/catalog/troubleshooting-the-catalog/"
  force = true

[[redirects]]
  from = "/docs/details/validator/"
  to = "/docs/catalog/validator/"
  force = true

[[redirects]]
  from = "/docs/details/ownership/"
  to = "/docs/catalog/ownership/"
  force = true

