# When Backstage was first released, it didn't have a service catalog at all. I wrote
# one blog post before the service catalog came along and another afterwards.
# Now that the service catalog is part of the default Backstage experience, these posts are
# essentially duplicate content.
[[redirects]]
  from = "/blog/backstage-docker-compose/"
  to = "/blog/backstage-docker-service-catalog/"
  force = true

# Supporting a legacy URL scheme which existed when the site was first published.
[[redirects]]
  from = "/terms/"
  to = "/legal-notices/website-terms/"
  force = true

# Supporting a legacy URL scheme which existed when the site was first published.
[[redirects]]
  from = "/docs/openapi"
  to = "/docs/api/authorization"
  force = true

# Supporting top level link to the api documentation.
[[redirects]]
  from = "/docs/api"
  to = "/docs/api/authorization"
  force = true

# Supporting a legacy URL scheme which existed when the site was first published.
[[redirects]]
  from = "/privacy/"
  to = "/legal-notices/privacy-notice/"
  force = true

[[redirects]]
  from = "/careers/"
  to = "https://careers.roadie.io"
  force = true

[[redirects]]
  from = "/careers/*"
  to = "https://careers.roadie.io"
  force = true

# Proxy for the plausible.io tracker. https://plausible.io/docs/proxy/guides/netlify
[[redirects]]
  from = "/plaus/js/script.js"
  to = "https://plausible.io/js/plausible.js"
  status = 200
  force = true

# Proxy for the plausible.io tracker. https://plausible.io/docs/proxy/guides/netlify
[[redirects]]
  from = "/plaus/api/event"
  to = "https://plausible.io/api/event"
  status = 200
  force = true

# Supporting external links to a policy which was orignally put on the website with a
# mis-spelled URL.
[[redirects]]
  from = "/legal-notices/evaluation-licence/"
  to = "/legal-notices/evaluation-license/"
  force = true

# Supporting external links to a policy which was orignally put on the website with a
# mis-spelled URL.
[[redirects]]
  from = "/legal-notices/evaluation-licence/v1/"
  to = "/legal-notices/evaluation-license/v1/"
  force = true

# Supporting US and UK spelling of modelling and modeling. The single-l version is linked from
# few places on the web.
[[redirects]]
  from = "/blog/modeling-software-backstage/"
  to = "/blog/modelling-software-backstage/"
  force = true

[[redirects]]
  from = "/docs/details/whitelisting-roadie-traffic/"
  to = "/docs/details/allowlisting-roadie-traffic/"
  force = true

[[redirects]]
  from = "/docs/getting-started/openapi-specs"
  to = "/docs/details/openapi-specs/"
  force = true

[[redirects]]
  from = "/docs/getting-started/getting-started-for-admins/"
  to = "/docs/getting-started/adding-a-catalog-item/"
  force = true

[[redirects]]
  from = "/docs/integrations/github-app-permissions/"
  to = "/docs/details/github-app-permissions/"
  force = true

[[redirects]]
  from = "/docs/getting-started/updating-the-ui/"
  to = "/docs/details/updating-the-ui/"
  force = true

[[redirects]]
  from = "/docs/integrations/required-annotations/"
  to = "/docs/details/required-metadata/"
  force = true

[[redirects]]
  from = "/docs/configurations/tech-radar/"
  to = "/docs/integrations/tech-radar/"
  force = true

# We are inundated by spam security reports since we added this. It's not worth it.
[[redirects]]
  from = "/security/responsible-disclosure/"
  to = "/"
  force = true

# We'll create a dedicated landing page for people coming from KubeCon
[[redirects]]
  from = "/kubernetes/"
  to = "/backstage/plugins/kubernetes/"
  force = true

# To be later filled in with a typeform URL
[[redirects]]
  from = "/techinsights-demo-backstagecon/"
  to = "/request-demo/"
  force = true

# There's no generic product page so we redirect to the first one
[[redirects]]
  from = "/product/"
  to = "/product/catalog/"
  force = true

[[redirects]]
  from = "/docs/scaffolder-cookbook/*"
  to = "/docs/scaffolder/:splat"
  force = true

[[redirects]]
  from = "/docs/scaffolder/call-external-api"
  to = "/docs/scaffolder/recipes/call-external-api"
  force = true

[[redirects]]
  from = "/docs/scaffolder/debug-template"
  to = "/docs/scaffolder/recipes/debug-template"
  force = true

[[redirects]]
  from = "/docs/details/scaffolder/"
  to = "/docs/scaffolder/writing-templates/"
  force = true

[[redirects]]
  from = "/docs/custom-plugins/"
  to = "/docs/custom-plugins/getting-started/"
  force = true

[[redirects]]
  from = "/docs/custom-plugins/proxy/"
  to = "/docs/custom-plugins/connectivity/proxy/"
  force = true

[[redirects]]
  from = "/docs/integrations/home-page-markdown/"
  to = "/docs/integrations/markdown-card/"
  force = true

[[redirects]]
  from = "/docs/details/location-management/"
  to = "/docs/catalog/location-management/"
  force = true

[[redirects]]
  from = "/docs/details/showing-dependencies/"
  to = "/docs/catalog/showing-dependencies/"
  force = true

[[redirects]]
  from = "/docs/details/decorating-components/"
  to = "/docs/catalog/decorating-components/"
  force = true

[[redirects]]
  from = "/docs/details/unregister-components/"
  to = "/docs/catalog/unregister-components/"
  force = true

[[redirects]]
  from = "/docs/details/previewing-changes/"
  to = "/docs/catalog/previewing-changes/"
  force = true

[[redirects]]
  from = "/docs/details/troubleshooting-the-catalog/"
  to = "/docs/catalog/troubleshooting-the-catalog/"
  force = true

[[redirects]]
  from = "/docs/details/validator/"
  to = "/docs/catalog/validator/"
  force = true

[[redirects]]
  from = "/docs/details/ownership/"
  to = "/docs/catalog/ownership/"
  force = true

[[redirects]]
  from = "/docs/getting-started/create-admin-group/"
  to = "/docs/getting-started/assigning-admins/"
  force = true

# At some point we decided to switch to the US spelling of modeling.
[[redirects]]
  from = "/docs/catalog/modelling-entities/ "
  to = "/docs/catalog/modeling-entities/"
  force = true

[[redirects]]
  from = "/local"
  to = "/request-demo"
  force = true

[[redirects]]
  from = "/local/"
  to = "/request-demo"
  force = true

#
# Redirects resulting from moving Backstage Weekly issues out of /blog/ and over
# to /backstage-weekly/. 
# https://app.shortcut.com/larder/story/29383/migrate-backstage-weekly-to-dedicated-content-model
#
# The following inconsistencies/typos were found with Backstage Weekly entries during the migration:
#
#   - Issue 9 was never added to the website in the first place, so it doesn't need a redirect.
#   - Issue 24 was posted with the wrong issue number in the URL.
#   - 30, 31 and 32 were never on the website, so no redirect is needed.
#   - Issue 65 was incorrectly publushed with the same slug as issue 64. So we never had an issue
#     65 on the website in the first place. Therefore it needs no redirect.
#   - Issue 80 was incorrectly published with '90' in the URL. I presume it was a typo at the time
#     the post was written.
#
# These first few are special cases where backstage weekly issues where the URL doesn't map
# cleanly with the pattern:
#   
#   from = "/blog/backstage-weekly-[N]-[rest of slug]"
#   to = "/backstage-weekly/[N]-[rest-of-slug]"

[[redirects]]
  from = "/blog/roadie-rundown-1/"
  to = "/backstage-weekly/roadie-rundown-1/"
  force = true

[[redirects]]
  from = "/blog/roadie-rundown-2/"
  to = "/backstage-weekly/roadie-rundown-2/"
  force = true

[[redirects]]
  from = "/blog/ga4-support-new-backend-going-ga/"
  to = "/backstage-weekly/86-ga4-support-new-backend-going-ga/"
  force = true

[[redirects]]
  from = "/blog/what-a-holistic-idp-looks-like/"
  to = "/backstage-weekly/87-what-a-holistic-idp-looks-like/"
  force = true

# This handles 2 special cases where we published a Backstage Weekly issue inder the slug:
#   "blog/roadies-backstage-weekly-[N]-[rest of slug]"
[[redirects]]
  from = "/blog/roadies-backstge-weekly-*"
  to = "/backstage-weekly/:splat:"
  force = true

# This handles all other Backstage Weekly redirects.
[[redirects]]
  from = "/blog/backstge-weekly-*"
  to = "/backstage-weekly/:splat"
  force = true
