site_name: 'Roadie Onboarding docs'
site_description: 'Documentation for using the Roadie application'

plugins:
  - techdocs-core

nav:
  - Getting started:
    - Getting started for admins: 'getting-started/getting-started-for-admins/index.md'
    - Adding components: 'getting-started/adding-components/index.md'
    - Openapi specs: 'getting-started/openapi-specs/index.md'
    - Scaffolding components: 'getting-started/scaffolding-components/index.md'
    - Technical documentation: 'getting-started/technical-documentation/index.md'
    - Updating the ui: 'getting-started/updating-the-ui/index.md'
    - User management: 'getting-started/user-management/index.md'
  - Integrations:
    - Argocd: 'integrations/argocd/index.md'
    - BuildKite: 'integrations/buildkite/index.md'
    - Bugsnag: 'integrations/bugsnag/index.md'
    - Catalog graph: 'integrations/catalog-graph/index.md'
    - Circleci: 'integrations/circleci/index.md'
    - Datadog: 'integrations/datadog/index.md'
    - Firehydrant: 'integrations/firehydrant/index.md'
    - Gcp: 'integrations/gcp/index.md'
    - Github org: 'integrations/github-org/index.md'
    - Github token: 'integrations/github-token/index.md'
    - Google oauth client: 'integrations/google-oauth-client/index.md'
    - Jira: 'integrations/jira/index.md'
    - Kubernetes: 'integrations/kubernetes/index.md'
    - Newrelic: 'integrations/newrelic/index.md'
    - Opsgenie: 'integrations/opsgenie/index.md'
    - Pagerduty: 'integrations/pagerduty/index.md'
    - Prometheus: 'integrations/prometheus/index.md'
    - Sentry: 'integrations/sentry/index.md'
    - Snyk: 'integrations/snyk/index.md'
    - Sonarqube: 'integrations/sonarqube/index.md'
    - Travis ci: 'integrations/travis-ci/index.md'
  - Configuration:
    - Tech radar: 'configuration/tech-radar/index.md'
  - Custom plugins:
    - Artifactory: 'custom-plugins/artifactory/index.md'
    - Configuring: 'custom-plugins/configuring/index.md'
